# This action will be executed when a tag is created and uploaded.
# More information: https://github.com/davidcopano/github-actions-docs

name: Generate Android Production APK

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Get code from current repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Add Android platform
        run: ionic cordova platform add android@latest

      - name: Generate production APK
        run: ionic cordova build android --no-confirm=yes --release --prod

      # IMPORTANT: To sign the APK, you must add these secrets in the Settings -> Secrets section of the Github repo.
      # More info: https://github.com/r0adkll/sign-android-release

      - name: Firmar APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: platforms/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "29.0.2"

      - name: Rename signed APK
        run: mv platforms/android/app/build/outputs/apk/release/app-release-unsigned-signed.apk platforms/android/app/build/outputs/apk/release/app-release-signed.apk

      - name: Upload generated and signed APK as artifact to Github
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: platforms/android/app/build/outputs/apk/release/app-release-signed.apk

      - name: Generate release to Github
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: platforms/android/app/build/outputs/apk/release/app-release-signed.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}