name: Generar APK Android

on: [push, pull_request]

jobs:
  build:
    name: Generar APK
    runs-on: ubuntu-latest
    steps:
      - name: Obtener código del repositorio
        uses: actions/checkout@v2

      - name: Preparar Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Preparar Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Instalar Cordova
        run: npm install -g cordova

      - name: Instalar Ionic
        run: npm install -g @ionic/cli

      - name: Instalar dependencias de la aplicación
        run: npm install

      - name: Añadir plataforma Android
        run: ionic cordova platform add android@latest

      - name: Generar APK de desarrollo
        run: ionic cordova build android --no-confirm=yes --debug --prod

      - name: Subir APK generada a Github
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk