name: Generate Android Development APK

on: [push, pull_request]

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Get code from current repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Add Android platform
        run: ionic cordova platform add android@latest

      - name: Generate debug APK
        run: ionic cordova build android --no-confirm=yes --debug --prod

      - name: Upload generated APK to Github
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk